@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@ct = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuS9oOS9oOS9oCIsImlhdCI6MTczMjY3MzgxMCwiZXhwIjoxNzMyODQ2NjEwfQ.Pt0MzSWq2xi2vkUPKwy0tdm2gSYI66wiIBN_WIuAp24



### @name 创建帖子
POST {{host}}/posts/add HTTP/1.1
Accept: {{ct}}
Content-Type: {{ct}}

{
  "title": "Nest入门到实践",
  "author": "Virgo",
  "content": "这是一篇用于nestjs入门的文章，看过该文章能掌握改库的基本用法。",
  "thumb_url": "https://p9-xtjj-sign.byteimg.com/tos-cn-i-73owjymdk6/07619ad363cd46738d56acf631991f59~tplv-73owjymdk6-jj-mark-v1:0:0:0:0:5o6Y6YeR5oqA5pyv56S-5Yy6IEAgX2ppYW5n:q75.awebp?rk3s=f64ab15b&x-expires=1732101242&x-signature=ezgoFZKMy55m5UX%2BhU0cYDG7VhY%3D",
  "type": 1
}

### @name 获取帖子列表 (需要登录时)
GET {{host}}/posts/list HTTP/1.1
Content-Type: {{ct}}
Authorization: Bearer {{token}}

{
  "pageNo": 1,
  "pageSize": 10
}


### @name get_tct_tenant_list
POST https://opsefcs.qa.tongcaitong.com/tenant/getTenants HTTP/1.1
Accept: {{ct}}
Content-Type: {{ct}}
Authorization: Bearer {{token}}

{
  "title": "帖子1",
  "author": "作者1",
  "content": "------1------",
  "thumb_url": "",
  "type": 1,
}

### @name 删除帖子
Delete {{host}}/posts/list/1 HTTP/1.1
Content-Type: {{ct}}
Authorization: Bearer {{token}}